# frozen_string_literal: true

require 'active_support/core_ext/hash'
require 'active_support/core_ext/hash/indifferent_access'
require 'active_support/core_ext/integer/time'
require 'active_support/core_ext/time/zones'
require 'httparty'
require 'net/http'
require 'net/https'
require 'nokogiri'
require 'nokogiri'
require 'timezone'
require 'uri'

require 'worksnaps/project'
require 'worksnaps/time_entry'
require 'worksnaps/timezone'
require 'worksnaps/user'
require 'worksnaps/user_assignment'
require 'worksnaps/summary'
require 'worksnaps/client'
